- descriptor: "pip-services-container:container-info:default:default:1.0"
  name: "pip-services-dummies"
  description: "Sample dummy microservice"
  
- descriptor: "pip-services-commons:logger:console:default:1.0"
  level: "trace"

- descriptor: "pip-services-dummies:controller:default:ctrl1:1.0"
  message: "Hello from dummy controller #1"

- type: "DummyController,./obj/examples/DummyController"
  message: "Hello from dummy controller #2"